---
- name: Set Selinuc to enforcing
  hosts: all
  become: yes
  tasks:
  - name: Set SELinux to enforcing
    ansible.builtin.include_role:
      name: redhat.rhel_system_roles.selinux
    vars:
      selinux_state: enforcing
